### ISSUE TITLE
Bug in gulpfile.js

### ISSUE THREAD

**Issue by SakhirAtwi** [WarenGonzaga/AnimateCSSPlugin#12]
@WarenGonzaga  There is some sort of glitch in gulpfile due to which the all the plugin files in /demo /build and downloadable are getting the initial comment twice,
![screenshot_20180806_013200](https://user-images.githubusercontent.com/42070051/43689795-f14561d0-9918-11e8-909c-5d44e3e3ecb9.png)

Even when the original source file have only one line,
![screenshot_20180806_013228](https://user-images.githubusercontent.com/42070051/43689803-0b7c0e96-9919-11e8-80dd-22b16e53e363.png)

**Comment by warengonzaga** [comment]
@SakhirAtwi please do `gulp clean` first and do `gulp build` and also make sure you have the latest commit.

**Comment by SakhirAtwi** [comment]
@WarenGonzaga  Yeah thats exactly what I'm doing gulp clean and then gulp (as default task also runs the build), but the problem persists.

**Comment by warengonzaga** [comment]
The thing is you are still using the old source file... please do refork... to fix your end and then all your codes should be on develop branch so we can prevent any issues...

**Comment by warengonzaga** [comment]
By reforking you should have the latest version without issue.
