### ISSUE TITLE
All Commits will be on Develop Branch

### ISSUE THREAD

**Issue by warengonzaga** [WarenGonzaga/AnimateCSSPlugin#14]
@SakhirAtwi I decided to separate the development from the master branch... please check out to the develop branch. All codes must be on develop branch.

**Comment by SakhirAtwi** [comment]
@WarenGonzaga Excellent idea, I was afraid coz of continues development, typos and bugs, master branch was gonna break one way or the other.

**Comment by warengonzaga** [comment]
alright, @SakhirAtwi do refork and push all your code on develop... and let me merge it..

**Comment by SakhirAtwi** [comment]
@WarenGonzaga K.

**Comment by warengonzaga** [comment]
Alright! @SakhirAtwi
