### ISSUE TITLE
Please update the github pages site for the project.

### ISSUE THREAD

**Issue by SakhirAtwi** [WarenGonzaga/AnimateCSSPlugin#2]
@WarenGonzagaOfficial I think you are busy or something, but I am seriously interested in your project. I have already created 35 news animations for your plugin and will create the rest in a day or 2. It think it would be something quite valuable towards GSAP. My request is to please update your Plugin site as it is still running the older version.

**Comment by warengonzaga** [comment]
Alright! @SakhirAtwi for being interested in my project, yes you are right I am busy on weekdays but still need to be active to open source projects such this... will review your commits and will merge :)

**Comment by warengonzaga** [comment]
@SakhirAtwi I made a bunch of updates... please rebase your code :) you should get the updated files and commit it again and I will review it. Thanks for your contribution.
